// Download all 13 Ginni knowledge-base files into src/data/ginni-kb/ so the
// reading engine is 100% offline. Run once (needs internet + Node 18+):
//
//     node scripts/fetch-kb.mjs
//
// It writes each <topic>.json and regenerates src/data/ginni-kb/index.js to
// require every file it fetched. Re-run any time to refresh from the source.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const BASE = 'https://raw.githubusercontent.com/devthedivinetarot/tdt-ginni/main/app/public/ginni-kb/';
const FILES = [
  'universe_guidance', 'yes_no', 'connection', 'soulmate', 'life_partner',
  'shaadi', 'baby', 'union', 'third_party_end', 'partner_feelings',
  'partner_action', 'monthly', 'relationship_ppf',
];

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '..', 'src', 'data', 'ginni-kb');
fs.mkdirSync(OUT, { recursive: true });

if (typeof fetch !== 'function') {
  console.error('This script needs Node 18+ (global fetch). Please upgrade Node.');
  process.exit(1);
}

const saved = [];
for (const f of FILES) {
  try {
    const res = await fetch(BASE + f + '.json');
    if (!res.ok) { console.warn(`skip  ${f}  (HTTP ${res.status})`); continue; }
    const text = await res.text();
    JSON.parse(text); // validate before writing
    fs.writeFileSync(path.join(OUT, f + '.json'), text);
    saved.push(f);
    console.log(`saved ${f}.json`);
  } catch (e) {
    console.warn(`fail  ${f}  (${e.message})`);
  }
}

// Regenerate the bundle index so Metro statically bundles every fetched file.
const lines = saved.map((f) => `  ${JSON.stringify(f)}: require('./${f}.json'),`).join('\n');
const index =
  '// AUTO-GENERATED by scripts/fetch-kb.mjs — bundled ginni-kb topic files.\n' +
  'export default {\n' + lines + '\n};\n';
fs.writeFileSync(path.join(OUT, 'index.js'), index);

console.log(`\nBundled ${saved.length}/${FILES.length} topic files → src/data/ginni-kb/`);
console.log('Now run:  npx expo start -c');
